-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'EXPORT_USER_DATA';
ALTER TYPE "AuditAction" ADD VALUE 'RESTORE_USER';
ALTER TYPE "AuditAction" ADD VALUE 'LINK_AFFILIATE';
ALTER TYPE "AuditAction" ADD VALUE 'UNLINK_AFFILIATE';
ALTER TYPE "AuditAction" ADD VALUE 'SYNC_STRIPE';
ALTER TYPE "AuditAction" ADD VALUE 'GRANT_FREE_MONTHS';
ALTER TYPE "AuditAction" ADD VALUE 'CONVERT_TO_PAID';
